### ISSUE TITLE
「砒」不讀「ㄆㄨ」吧？

### ISSUE THREAD

**Issue by 307587** [baopaau/rime-bepemefe#2]
https://zh.wikiversity.org/wiki/Special:%E6%90%9C%E7%B4%A2?fulltext=%E9%8D%B5%E5%85%A5%E6%BC%A2%E5%AD%97%E3%80%81%E9%9F%B3%E7%AF%80%E6%88%96%E9%9F%BB%E7%9B%AE%E9%80%B2%E8%A1%8C%E6%AA%A2%E7%B4%A2&fulltext=Search&prefix=Subject%3A%E8%80%81%E5%9C%8B%E9%9F%B3&search=%E7%A0%92&ns0=1&searchToken=2gab7c68od1c2gv16u929u0uq

**Comment by baopaau** [comment]
感謝勘誤，字音已更正
